'use client';
import { useEffect, useState } from 'react';

const pieces=[['grip',-1.75,-.35,-10],['body',0,0,0],['sensor',.38,.08,5],['board',1.05,.2,12],['screen',1.72,.18,7],['lens-ring',.08,.02,0],['lens-glass',.7,-.02,-4],['lens',1.45,-.04,4],['prism',-.15,-1,-7]] as const;
const works=[
  {n:'01',title:'Eventos',img:'/images/eventos.jpg',text:'Fotografias para eventos sociais, culturais e corporativos — criativas, ágeis e alinhadas às necessidades de cada cliente.'},
  {n:'02',title:'Retratos',img:'/images/retratos.png',text:'Direção leve e atenção à expressão. Imagens que comunicam presença, intenção e estilo com simplicidade e cuidado.'},
  {n:'03',title:'Casamentos',img:'/images/casamentos.png',text:'Um registro discreto e sensível, construindo um acervo fiel e afetivo de cada história vivida.'},
  {n:'04',title:'Gastronomia',img:'/images/gastronomia.jpg',text:'Clareza e apelo visual para cardápios, catálogos e campanhas que comunicam sabor, qualidade e identidade.'},
  {n:'05',title:'Vídeos',img:'/images/videos.jpg',text:'Filmes sob medida para marcas, projetos culturais e pessoas criativas, com ritmo e linguagem alinhados ao propósito.'},
  {n:'06',title:'Curadoria musical',img:'/images/curadoria.jpg',text:'Atmosferas sonoras para eventos, marcas e espaços. Repertório, pesquisa e estratégia para encontrar o tom exato.'}
];
function useProgress(){const[p,setP]=useState(0);useEffect(()=>{let f=0;const u=()=>{f=0;const s=document.querySelector<HTMLElement>('.camera-scene');if(!s)return;const r=s.getBoundingClientRect(),d=s.offsetHeight-innerHeight;setP(Math.max(0,Math.min(1,-r.top/Math.max(d,1))))};const on=()=>{if(!f)f=requestAnimationFrame(u)};u();addEventListener('scroll',on,{passive:true});addEventListener('resize',on);return()=>{removeEventListener('scroll',on);removeEventListener('resize',on);cancelAnimationFrame(f)}},[]);return p}
function Lit({children,className=''}:{children:string,className?:string}){return <span className={`lit ${className}`}>{children.split('').map((c,i)=><span key={i} style={{'--i':i} as React.CSSProperties}>{c===' '?'\u00a0':c}</span>)}</span>}
function Observe(){useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle('seen',e.isIntersecting)),{threshold:.18});document.querySelectorAll('.reveal,.lit').forEach(e=>io.observe(e));return()=>io.disconnect()},[]);return null}
export default function Home(){const p=useProgress(),explode=Math.sin(Math.PI*Math.min(1,p*1.12)),rotate=Math.sin(Math.PI*p)*7;const[menu,setMenu]=useState(false);return <main><Observe/><header className="topbar"><a href="#inicio" className="mini-logo">AKAIA®</a><span>BH · BRASIL</span><button aria-label="Abrir menu" onClick={()=>setMenu(!menu)}>{menu?'FECHAR':'MENU'}</button></header>{menu&&<nav className="menu"><a onClick={()=>setMenu(false)} href="#trabalhos">Trabalhos</a><a onClick={()=>setMenu(false)} href="#sobre">Sobre</a><a onClick={()=>setMenu(false)} href="#contato">Contato</a></nav>}
<section className="camera-scene" id="inicio"><div className="camera-sticky"><div className="grain"/><p className="eyebrow">ESTÚDIO DE FOTOGRAFIA + FILME</p><h1 aria-label="Akaia" className="brand">{'AKAIA'.split('').map((l,i)=><span key={i}>{l}</span>)}</h1><div className="camera" style={{transform:`translate(-50%,-48%) rotateY(${rotate}deg) scale(${1-explode*.06})`}} aria-label="Câmera sem marca se desmontando com a rolagem">{pieces.map(([name,x,y,r])=><div key={name} className={`part ${name}`} style={{transform:`translate(calc(-50% + ${x*explode*190}px), calc(-50% + ${y*explode*150}px)) rotate(${r*explode}deg)`}}/>)}</div><p className="hero-note">IMAGENS QUE GUARDAM<br/>O QUE O TEMPO MOVE.</p><div className="scroll-cue"><span>DESLIZE PARA REVELAR</span><i/></div><div className="scene-counter">0{Math.min(3,Math.floor(p*4)+1)} / 03</div></div></section>
<section className="manifesto"><p className="kicker">UM ESTÚDIO, MUITAS FORMAS DE VER.</p><h2><Lit>Histórias reais.</Lit><br/><Lit className="serif">Presença em cada quadro.</Lit></h2><div className="manifesto-copy reveal"><p>Fotografia não é só o que permanece.</p><p>É o instante em que luz, pessoa e lugar se reconhecem. O Estúdio Akaia cria imagens e filmes para guardar memória, construir identidade e mover pessoas.</p></div></section>
<section className="work-intro" id="trabalhos"><p className="kicker">PORTFÓLIO SELECIONADO · 01—06</p><h2><Lit>O olhar muda.</Lit><br/><Lit>A essência fica.</Lit></h2></section>
<section className="works">{works.map((w,i)=><article className="work" key={w.title}><div className="work-sticky"><figure className="work-image"><img src={w.img} alt={`Fotografia de ${w.title} por Estúdio Akaia`}/><span>{w.n}</span></figure><div className="work-copy"><p>{w.n} / 06</p><h3><Lit>{w.title}</Lit></h3><p className="reveal">{w.text}</p><a href="#contato">CONVERSAR SOBRE UM PROJETO ↗</a></div></div></article>)}</section>
<section className="about" id="sobre"><div className="about-photo reveal"><img src="/images/danilo.jpg" alt="Danilo Alvarez, fotógrafo e fundador do Estúdio Akaia"/></div><div className="about-copy"><p className="kicker">SOBRE · DANILO ALVAREZ</p><h2><Lit>Curiosidade como método.</Lit></h2><div className="reveal"><p>Olá, me chamo Danilo Alvarez — pode me chamar de Dan. Nasci e cresci em Belo Horizonte e conheci a fotografia aos oito anos, com uma câmera analógica descartável.</p><p>Há mais de uma década trabalho entre casamentos, retratos, gastronomia, eventos, moda e produções audiovisuais. Coordenei o audiovisual do Galpão Cine Horto e também a Casa Camô, espaço dedicado à cultura e à formação.</p><p>O Estúdio Akaia atua com fotografia comercial, moda, vídeos publicitários, videoclipes, eventos, curtas, still para cinema e produções artísticas.</p></div></div></section>
<section className="quote"><p>“</p><h2><Lit>Fazer história é aprender a enxergar o que ainda não foi visto.</Lit></h2></section>
<footer id="contato"><p className="kicker">TEM UMA IDEIA?</p><h2><Lit>Vamos fazer</Lit><br/><Lit className="serif">história?</Lit></h2><p>Conte sua ideia, projeto ou consulte disponibilidade. Quanto mais detalhes você enviar, melhor poderemos responder.</p><a className="contact-button" href="https://wa.me/5531998662272">INICIAR CONVERSA ↗</a><div className="footer-line"><span>BELO HORIZONTE · BRASIL</span><a href="http://instagram.com/dan.alvarezzz">INSTAGRAM ↗</a><span>© {new Date().getFullYear()} AKAIA</span></div></footer>
</main>}
